[workspace]
resolver = "2"

members = [
    "resources/how-big-is-your-future",
    "resources/tokio-with-the-console",
    "resources/tracing-examples",
    "resources/tracing-reload",
    "resources/tracing-tokio-tasks",
    "resources/track_caller",
    "resources/understanding-async-await",
]
