[workspace]
resolver = "2"

members = [
    "resources/logging-1",
    "resources/track_caller",
    "resources/understanding-async-await",
    "resources/tracing-reload",
    "resources/tracing-tokio-tasks",
    "resources/debugging-tokio-instrumentation",
]
