[package]
name = "mini-subscribed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console-subscriber = "0.1"
hdrhistogram = { version = "7.5.2", default-features = false, features = ["serialization"] }
rand = "0.8"
tokio = { version = "1", features = ["full", "tracing"] }
tonic = { version = "0.9", features = ["transport"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
