vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    theme-id: 200
    pad: 30
  }
}
Kubernetes namespace: {
    loadgen: Load Generator
    app: Application Pod
}

Kubernetes namespace.loadgen -> Kubernetes namespace.app


