direction: right
start: "Initial" {
  shape: circle
  width: 30
  height: 30
  style.fill: "#776594"
}
end: "Final" {
  shape: circle
  width: 30
  height: 30
  style.fill: "#776594"
}
Init: Init \{ name: String \}
Done: Done

start -> Init: constr. {
  direction: down
}
Init -> Done: poll()
Done -> end: drop
