direction: right
start: "Initial" {
  shape: circle
  width: 30
  height: 30
  style.fill: "#776594"
}
end: "Final" {
  shape: circle
  width: 30
  height: 30
  style.fill: "#776594"
}
Init: Init \{ data \}
Yielded: Sleep \{ guard, _data \}
Done: Done

start -> Init: constr.
Init -> Yielded: poll() -> Poll::Pending
Yielded -> Done: poll() -> Poll::Ready
Done -> end: drop
