shape: sequence_diagram

runtime: Async Runtime
main: main()
main_task: task (main.body)
fn_pending: pending()
pending: Pending

main.fn -> runtime.block: block_on()
runtime.block -> main_task.fn: poll()

main_task.fn -> fn_pending.fn: pending()
main_task.fn <- fn_pending.fn: Pending {
  style.stroke-dash: 5
}

main_task.fn -> pending.future: poll()
main_task.fn <- pending.future: Pending() {
  style.stroke-dash: 5
}

runtime.block <- main_task.fn: Pending() {
  style.stroke-dash: 5
}
runtime.block -> runtime.block: park_thread()
