shape: sequence_diagram

main: async main()
fn_ready: ready()
ready: Ready
sa: (Side Effects)

main.task -> sa: println!("Before ready().await")

main.task -> fn_ready.fn: ready()
main.task <- fn_ready.fn: Ready {
  style.stroke-dash: 5
}

main.task -> ready.future: poll()
ready.future -> sa: println!("Ready: poll()")
main.task <- ready.future: Poll::Ready(()) {
  style.stroke-dash: 5
}

main.task -> sa: println!("After ready().await")
