shape: sequence_diagram

runtime: Async Runtime
main: main()
main_task: task (main.body)
future1: task (spawn_again)
future2: task (do_nothing)
future3: do_nothing

main.fn -> runtime.block: block_on()

runtime.block -> main_task.poll1: poll()
main_task.poll1 -> runtime.block: spawn(Future1)
main_task.poll1 -> future3.poll1: poll()
main_task.poll1 <- future3.poll1: Poll::Ready
main_task.poll1 -> main_task.poll1: yield_now()
runtime.block <- main_task.poll1: Poll::Pending {
  style.stroke-dash: 5
}

runtime.block -> future1.poll1: poll()
future1.poll1 -> runtime.block: spawn(Future2)
runtime.block <- future1.poll1: Poll::Ready {
  style.stroke-dash: 5
}

runtime.block -> future2.poll1: poll()
runtime.block <- future2.poll1: Poll::Ready {
  style.stroke-dash: 5
}

runtime.block -> main_task.poll2: poll()
main_task.poll2 -> main_task.poll2: yield_now()
runtime.block <- main_task.poll2: Poll::Pending {
  style.stroke-dash: 5
}
