direction: right
start: "Initial" {
  shape: circle
  width: 30
  height: 30
  style.fill: "#776594"
}
end: "Final" {
  shape: circle
  width: 30
  height: 30
  style.fill: "#776594"
}
not_yielded: yielded = false
yielded: yielded = true

start -> not_yielded: constr.
not_yielded -> yielded: poll() -> Poll::Pending()
yielded -> yielded: poll() -> Poll::Ready(())
yielded -> end: drop
