shape: sequence_diagram

runtime: Async Runtime
main: main()
main_task: task (main.body)
fn_yield_now: yield_now()
yield_now: YieldNow
waker: Waker
sa: (Side Effects)

main.fn -> runtime.block: block_on()
runtime.block -> main_task.poll1: poll()

main_task.poll1 -> sa: println!("Before yield_now().await")

main_task.poll1 -> fn_yield_now.fn: yield_now()
main_task.poll1 <- fn_yield_now.fn: YieldNow {
  style.stroke-dash: 5
}

main_task.poll1 -> yield_now.poll1: poll()
yield_now.poll1 -> sa: println!("YieldNow: poll()")
yield_now.poll1 -> yield_now.poll1: self.yielded = true
yield_now.poll1 -> waker.fn: wake_by_ref()
waker.fn -> runtime.block.schedule: schedule(task)
waker.fn <- runtime.block.schedule: {
  style.stroke-dash: 5
}
yield_now <- waker.fn: {
  style.stroke-dash: 5
}
main_task.poll1 <- yield_now.poll1: Pending() {
  style.stroke-dash: 5
}
runtime.block <- main_task.poll1: Pending() {
  style.stroke-dash: 5
}

runtime.block -> main_task.poll2: poll()
main_task.poll2 -> yield_now.poll2: poll()
yield_now.poll2 -> sa: println!("YieldNow: poll()")
main_task.poll2 <- yield_now.poll2: Ready(()) {
  style.stroke-dash: 5
}
main_task.poll2 -> sa: println!("After yield_now().await")

runtime.block <- main_task.poll2: Ready(()) {
  style.stroke-dash: 5
}
main.fn <- runtime.block: () {
  style.stroke-dash: 5
}
